Add tomcat base configuration
GoogleCloudPlatform/tomcat-runtime pull request #22
Opened 2017-05-31 18:09 UTC by cassand

This add a default configuration for the tomcat instance as well as documentation.

The configuration is based on the documents cited in #16 and apply #19  #20  #21.

2017-05-31 21:14 UTC, aslo commented on tomcat/src/main/tomcat-base/conf/web.xml
> +<?xml version="1.0" encoding="UTF-8"?>
Does this file contain some custom options for customizing the tomcat installation? If so, it would be great if there were a way to separate the custom overrides from this large default web.xml file. Is it possible to only include the properties that we're customizing?

2017-05-31 21:14 UTC, aslo commented on README.md
> +# Building the image
This type of information should probably go in a separate readme file called DEVELOPING.md, like we've done for the jetty and openjdk runtimes. You should reference the DEVELOPING.md file at the bottom of this one.

2017-05-31 21:22 UTC, cassand commented on README.md
> +# Building the image
Yes this part should belong to DEVELOPING.md, however, it might be interesting to keep it here before the first release, as it is a mandatory step.

2017-05-31 21:26 UTC, meltsufin commented
I would suggest just copying the default configuration first, and then applying fixes to #16 #19 #20 #21 in separate PRs so that the changes that address the issues are clearly visible.

2017-05-31 21:32 UTC, aslo commented on README.md
> +# Building the image
What if you move this to DEVELOPING.md and add a line here that says "This image has not yet been released. For instructions on building from source, see DEVELOPING.md"

2017-05-31 21:55 UTC, cassand commented on tomcat/src/main/tomcat-base/conf/web.xml
> +<?xml version="1.0" encoding="UTF-8"?>
Yes, I have updated web.xml with only the needed configuration

2017-06-01 13:45 UTC, aslo approved these changes

2017-06-01 14:11 UTC, meltsufin requested changes
I think there is too much going on in this PR. We're trying to add base configuration and modify it, and we're also trying to handle running under non-root user. I would split this into several PRs. 1) Add default configuration that the official distribution of tomcat provides -- simple. 2) Then make individual changes from that base to apply security/perf improvements. 3) Handle running under tomcat user.

This way it will be clear what is changing and why from the default Tomcat config.

2017-06-01 14:11 UTC, meltsufin commented on README.md
> +USER tomcat
Can we just wrap `catalina.sh` and change user there before starting the server?

2017-06-01 14:11 UTC, meltsufin commented on tomcat/src/test/resources/structure.yaml
> -  path: '${tomcat.base}/conf/catalina.properties'
Is `catalina.properties` not required?

2017-06-01 15:02 UTC, closed without merging