Refactor ci build scripts by using configuration generated by maven
GoogleCloudPlatform/tomcat-runtime pull request #42
Opened 2017-06-08 18:07 UTC by cassand

This PR remove configurations hard-coded into bash script and use maven properties instead.

A bash library to execute maven command with a consistent environment and to retrieve maven configuration is introduced in scripts/utils/maven.sh.

2017-06-08 21:25 UTC, aslo requested changes

2017-06-08 21:25 UTC, aslo commented on scripts/ci/build.sh
> +  export DOCKER_TAG_LONG=$(git rev-parse --short HEAD)
Do you need to be at the git repository root to execute this command? I would have thought you can run this from anywhere within the repository.

2017-06-08 21:25 UTC, aslo commented on scripts/build.sh
> +  maven_utils::execute $@ clean install
I don't think it's necessary to pass all arbitrary arguments to this script into maven like this - I actually think it adds more potential to confuse people. I'd prefer if this script only passed in the maven arguments/properties that are necessary.

2017-06-08 22:16 UTC, cassand commented on scripts/build.sh
> +  maven_utils::execute $@ clean install
Indeed, `maven_utils::execute` can be used to pass arbitrary arguments so this is not needed anymore

2017-06-09 14:05 UTC, meltsufin commented
@aslo and @cassand I'm not sure how we got here, but all of these scripts are getting really confusing for me. I'm having to think real hard every time I look at this to understand what's used where and why. Maybe renaming the scripts and adding more comments would help. I don't know. I'm open to ideas to make this better.

2017-06-09 15:38 UTC, aslo commented
@meltsufin Agreed - we should probably be a bit more principled in what goes into these scripts. Let's chat about it offline.

2017-06-09 15:42 UTC, meltsufin approved these changes

2017-06-09 17:34 UTC, aslo approved these changes

2017-06-09 17:35 UTC, merged