Refactor CI and release script
GoogleCloudPlatform/tomcat-runtime pull request #44
Opened 2017-06-09 20:55 UTC by cassand

The release is now handled by a separate script in order to transition to a build entirely handled by cloudbuild (ci/release.sh).

The maven commands during integration test is now executed in the project root directory (ci/script.sh)

2017-06-09 21:47 UTC, aslo submitted a review, later dismissed

2017-06-12 13:43 UTC, meltsufin requested changes

2017-06-12 13:43 UTC, meltsufin commented on scripts/ci/release.sh
> +  DOCKER_NAMESPACE="gcr.io/$(gcloud info \
We're duplicating this logic in `build.sh`. Can we factor it out? Maybe rename `maven.sh` to jsut `utils.sh` and put it in there?

2017-06-12 14:49 UTC, cassand commented on scripts/ci/release.sh
> +  DOCKER_NAMESPACE="gcr.io/$(gcloud info \
Indeed as more functionalities using the gcloud cli may appear I added a new library (utils/gcloud.sh)

2017-06-12 14:57 UTC, meltsufin approved these changes

2017-06-12 14:58 UTC, merged