Set APP_DEST env variable
GoogleCloudPlatform/tomcat-runtime pull request #58
Opened 2017-06-23 15:48 UTC by aslo

Sets a variable to show where web apps should be added in child containers.

2017-06-23 16:05 UTC, meltsufin commented
Should it be `APP_DEST` or `APP_DESTINATION`? Seems to be an inconsistency between the PR title and the code.

2017-06-23 16:11 UTC, aslo commented
Either is fine with me - let's go with app_destination

2017-06-23 21:43 UTC, cassand approved these changes

2017-06-23 21:45 UTC, cassand requested changes

2017-06-23 21:45 UTC, cassand commented on tomcat/src/main/docker/Dockerfile
> +ENV APP_DESTINATION ROOT.war
`${CATALINA_BASE}/webapps/ROOT.war` would be more appropriate, if we decide later to change the `WORKDIR`

2017-06-26 14:54 UTC, aslo commented on tomcat/src/main/docker/Dockerfile
> +ENV APP_DESTINATION ROOT.war
:+1:

2017-06-26 17:50 UTC, cassand approved these changes

2017-06-26 17:53 UTC, merged