Support excluding URLs in distributed session replication
GoogleCloudPlatform/tomcat-runtime pull request #77
Opened 2017-08-10 21:02 UTC by cassand

Fix #75

2017-08-11 14:25 UTC, meltsufin requested changes
Some nits, but otherwise looks good.

2017-08-11 14:25 UTC, meltsufin commented on README.md
> +| session.DatastoreValve.ignoredUriPattern | [Pattern](https://docs.oracle.com/javase/8/docs/api/java/util/regex/Pattern.html) specifying which Uri to ignore when persisting sessions. | null |
Specify that it's a regex pattern and give an example somewhere.
Also, in the description use "URI" (all caps).

I think `session.datastore.uriExcludePattern` is a better name. Also, I think the other variables should be renamed to `session.datastore.namespace`, etc. "DatastoreStore" sounds odd.

2017-08-11 14:25 UTC, meltsufin commented on tomcat-gcp-lib/src/main/java/com/google/cloud/runtimes/tomcat/session/DatastoreValve.java
> +  private boolean isUriIgnored(String uri) {
`isUriExcluded`

2017-08-11 14:25 UTC, meltsufin commented on tomcat-gcp-lib/src/main/java/com/google/cloud/runtimes/tomcat/session/DatastoreValve.java
> +  private String ignoredUriPattern;
`uriExcludePattern`

2017-08-11 14:25 UTC, meltsufin commented on tomcat/src/main/tomcat-base/conf/catalina.properties
> +session.DatastoreValve.ignoredUriPattern=
Put a comment above describing the property.

2017-08-11 14:25 UTC, meltsufin commented on tomcat-gcp-lib/src/main/java/com/google/cloud/runtimes/tomcat/session/DatastoreValve.java
> +    return ignoredUriPattern != null && Pattern.matches(ignoredUriPattern, uri);
Should we check if it's an empty string as well?

2017-08-11 15:37 UTC, cassand commented on README.md
> +| session.DatastoreValve.ignoredUriPattern | [Pattern](https://docs.oracle.com/javase/8/docs/api/java/util/regex/Pattern.html) specifying which Uri to ignore when persisting sessions. | null |
I opened a separate issue for renaming the properties #78.

2017-08-14 14:22 UTC, aslo requested changes
Just a few small comments as well. Looks good overall!

2017-08-14 14:22 UTC, aslo commented on README.md
> +| session.DatastoreValve.uriExcludePattern | [Pattern](https://docs.oracle.com/javase/8/docs/api/java/util/regex/Pattern.html) specifying which Uri to ignore when persisting sessions. | null |
+1 to changing `Uri` -> `URI`. 

Also, an example of configuring the `TOMCAT_PROPERTIES` env variable in app.yaml would be really helpful here. For example, I'd wonder how to configure multiple properties. Should they be comma-separated? Semicolon-separated? etc.

2017-08-14 14:22 UTC, aslo commented on tomcat-gcp-lib/src/main/java/com/google/cloud/runtimes/tomcat/session/DatastoreValve.java
> +      log.debug("Session not persisted");
It would be helpful to include the reason the session is not persisted. "Session not persisted because URI /foo/bar is excluded".

2017-08-14 14:53 UTC, meltsufin commented on README.md
> +  TOMCAT_PROPERTIES: session.DatastoreStore.sessionMaxInactiveTime=2000,session.DatastoreValve.uriExcludePattern=/_ah/health
I would prefer an example that uses regex rather than just `/_ah/health`.

2017-08-14 14:55 UTC, aslo commented on tomcat-gcp-lib/src/main/java/com/google/cloud/runtimes/tomcat/session/DatastoreValve.java
> +      log.debug("Session not persisted (Non existent or the URI is ignored");
Looks like you're missing a `)`.

2017-08-14 15:06 UTC, meltsufin commented on README.md
> +  TOMCAT_PROPERTIES: session.DatastoreStore.sessionMaxInactiveTime=2000,session.DatastoreValve.uriExcludePattern=^/_ah/*
I think you meant `^/_ah/.*$`. Also, please make sure that it actually works.

2017-08-14 15:30 UTC, aslo approved these changes

2017-08-14 15:49 UTC, meltsufin approved these changes

2017-08-14 15:53 UTC, merged